# Generated by Django 5.0.1 on 2024-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productinquiry',
            name='inquirystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
